name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'  # 每周五北京时间20时运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2
        
      - name: 安装 Playwright 所需依赖
        run: |
          npx playwright install-deps

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiofiles requests

      - name: Install Playwright Browsers  # 安装浏览器
        run: |
          playwright install firefox
          
      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.3
        with:
           stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
           mode: client    # Optional. Support [ wireguard, client ]. Default is wireguard.

      - name: 运行登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          python login_script.py

      - name: Renew README.md
        run: |
            DATE=$(date "+%Y/%m/%d %H:%M:%S")
            echo "${DATE}" > README.md
            git checkout --orphan tmp_work
            git branch -d main
            echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Auto deploy by Github Actions, ${{ env.DATE }}
          create_branch: true
          branch: main
          push_options: --force

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repository: ${{ github.repository }}
          older-than-seconds: 3600

